return {
  -- Themery: theme switcher
  {
    "zaldih/themery.nvim",
    lazy = false,
    -- enabled = false,
    config = function()
      require("themery").setup({
        livePreview = true,
        themes = {
          -- Built-in Neovim colorschemes
          -- "blue", "darkblue", "delek", "desert", "elflord", "evening",
          -- "habamax", "industry", "koehler", "morning", "murphy",
          -- "pablo", "peachpuff", "quiet", "ron", "shine", "slate",
          -- "torte", "zellner",

          -- Community colorschemes
          "ayu-dark",
          "ayu-light",
          "ayu-mirage",
          "carbonfox",
          "catppuccin-frappe",
          "catppuccin-latte",
          "catppuccin-macchiato",
          "catppuccin-mocha",
          "dracula",
          "edge",
          "everforest",
          -- "gruvbox",
          -- "gruvbox-baby",
          -- "gruvbox-flat",
          "gruvbox-material",
          -- "gruvbox-modern",
          "kanagawa-dragon",
          "kanagawa-lotus",
          "kanagawa-wave",
          "material",
          "melange",
          "monokai-pro",
          "nightfox",
          "nord",
          "nordfox",
          "onedark",
          "oxocarbon",
          "rose-pine",
          "rose-pine-dawn",
          "rose-pine-moon",
          "solarized",
          "solarized-osaka",
          "tokyonight-day",
          "tokyonight-moon",
          "tokyonight-night",
          "tokyonight-storm",
        },
      })
    end,
  },

  -- Theme plugins (alphabetized)
  { "Shatur/neovim-ayu" },
  { "catppuccin/nvim", name = "catppuccin" },
  { "Mofiqul/dracula.nvim" },
  { "sainnhe/edge" },
  { "sainnhe/everforest" },
  -- { "ellisonleao/gruvbox.nvim" },
  -- { "luisiacc/gruvbox-baby" },
  -- { "eddyekofo94/gruvbox-flat.nvim" },
  { "sainnhe/gruvbox-material" },
  -- { "neanias/gruvbox-modern" },
  { "rebelot/kanagawa.nvim" },
  { "marko-cerovac/material.nvim" },
  { "savq/melange-nvim" },
  { "loctvl842/monokai-pro.nvim" },
  { "tanvirtin/monokai.nvim" },
  { "EdenEast/nightfox.nvim" },
  { "shaunsingh/nord.nvim" },
  { "navarasu/onedark.nvim" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "rose-pine/neovim", name = "rose-pine" },
  { "maxmx03/solarized.nvim" },
  { "craftzdog/solarized-osaka.nvim" },
  { "folke/tokyonight.nvim" },
}
